### ISSUE TITLE
[Linux] segfaults

### ISSUE THREAD

**Issue by probonopd** [ShareXin/ShareXin#1]
```
linux@linux:~> Downloads/sharexin.AppImage 
Segmentation fault (core dumped)
linux@linux:~> cat /etc/os-release
NAME="openSUSE Leap"
VERSION="42.3"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="42.3"
PRETTY_NAME="openSUSE Leap 42.3"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:42.3"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```

**Comment by thebitstick** [comment]
I don't do much testing with on other distros. I might need to package on Debian stable (for old libraries).  
Not sure why Ubuntu and openSUSE cause problems when the binary _**seems**_ to work just fine on my distro (Arch) and Fedora.

**Comment by thebitstick** [comment]
I've compiled a openSUSE Leap AppImage.
Would be way easier if I could statically compile everything.

**Comment by probonopd** [comment]
I can confirm that the Ubuntu one works on Xubuntu 16.04.1 LTS. But ideally one AppImage, e.g., built on Ubuntu 1404 trusty, should work everywhere. This needs to be investigated.

**Comment by thebitstick** [comment]
Ideally yes, but compiling it dynamically on Arch gives libssl and libcrypto errors on Ubuntu and openSUSE (it works fine on Fedora).  
Compiling on Debian works fine on Arch only if Debian libraries are not included in the AppDir/usr/lib folder.  
The only real solution I see is static binary for ShareXin, but I think I'd need to compile OpenSSL with Musl.

**Comment by probonopd** [comment]
This is the first AppImage where such drastic measures would be required. I think it has to do with the selection of libraries that should and should not be bundled, i.e., https://github.com/AppImage/AppImages/blob/master/excludelist.

Some experimentation would be needed.

**Comment by thebitstick** [comment]
I think only OpenSSL needs to get experimented with.

**Comment by probonopd** [comment]
OpenSSL, sad as it is, probably needs to be bundled at the moment.

**Comment by thebitstick** [comment]
0.5.7 AppImage resolves OpenSSL issues.

**Comment by probonopd** [comment]
Thank you very much :+1:
