### ISSUE TITLE
Add Polish translation for new system tray option

### ISSUE THREAD

**Issue by thebitstick** [ShareXin/ShareXin#14]
@michcioperz could you translate this help message? I've added a system tray icon.

https://github.com/ShareXin/ShareXin/blob/e7626a0d5edfdd6369a113de4591bd2756db2363/src/lang/en.yml#L60

**Comment by Michcioperz** [comment]
What context is it used in?

**Comment by thebitstick** [comment]
I've updated it to "Use system tray icon", so in context it's put in the `--help` menu.
Using `--tray` uses a system tray, like ShareX
