### ISSUE TITLE
sharexin.desktop needs Type=Application

### ISSUE THREAD

**Issue by probonopd** [ShareXin/ShareXin#4]
desktop-file-validate says `sharexin.desktop: error: required key "Type" in group "Desktop Entry" is not present`.

Can be fixed by adding `Type=Application`.

Reference:
https://travis-ci.org/AppImage/AppImageHub/builds/266370509#L544

**Comment by thebitstick** [comment]
I'll be updating the current AppImage for 0.5.7.
I'll so be looking into Desktop File specifications. 
Thank you!
