### ISSUE TITLE
Error 5: t command unavailable Error 6: toot command unavailable

### ISSUE THREAD

**Issue by probonopd** [ShareXin/ShareXin#6]
When launching from the command line, I get

```
Error 5: t command unavailable
Error 6: toot command unavailable
```

What am I missing?

**Comment by thebitstick** [comment]
t and toot are for sending tweets to Twitter and sending toots to Mastodon.  
Currently I have to resort to external commands for using Twitter and Mastodon.  
Implementing a proper API for the two in Rust is a huge one on the TODO.

**Comment by probonopd** [comment]
Or pack those tools into the AppImage as well...

**Comment by thebitstick** [comment]
I've tried that.
I think it's actually impossible to pack the Ruby app `t` into AppImage,
and Python `toot` has issues as well.

**Comment by probonopd** [comment]
Well I wouldn't say "impossible" but you'd have to bundle the Python and Ruby stacks as well.

**Comment by thebitstick** [comment]
I just got Python to work thanks to virtualenv. toot works perfectly
Now if I can get Ruby to work...

Got Python working thanks to this: https://github.com/AppImage/AppImageKit/wiki/Bundling-Python-apps

**Comment by probonopd** [comment]
Check out https://github.com/AppImage/AppImages/blob/master/recipes/meta/travis.yml

**Comment by thebitstick** [comment]
Got it working but now I get a memory error on openSUSE, works everyelse.

**Comment by probonopd** [comment]
Make sure you are not bundling any of the libraries on the [excludelist](https://github.com/AppImage/AppImages/blob/master/excludelist).

**Comment by thebitstick** [comment]
Works now!
